### PR TITLE
Made more maven friendly and updated to 1.8.3

### PR DESCRIPTION
**Pull request by TheFatDemon**
I just moved stuff around and made it easier for IDE's like IntelliJ IDEA to use it without issues.

### CODE REVIEW

**Comment by TheFatDemon** [comment]
I was originally planning to attempt to fix a NullPointerException I was getting but I ended up not being able to figure it out so I just did this.

**Comment by Dart2112** [comment]
If you could remove the moving of the plugin.yml and config.yml Id be happy to merge it.

**Comment by TheFatDemon** [comment]
Just curious, any specific reason why the config and the plugin .yml files need to be in the root? Maven automatically copies them into the jar.

**Comment by Dart2112** [comment]
It just makes it easier for me to access them from other classes

**Comment by Dart2112** [comment]
Merged but I will be moving the files back once its done, Do you have an error for the null and does it still exist in the latest versions

**Comment by Dart2112** [comment]
What ever you did created 4 src files, All reverted exept pom, fixing the mess you made

**Comment by Dart2112** [comment]
I keep the files in the SRC file because I dont use maven to export, its only for CI

**Comment by jemcdevitt** [comment]
Similar error occurs if using /homelists or /listhome on a 1.13.2 base spigot server.  Using /listhomes does not generate the error but also does not present anything in the list.  The root cause of the error appears to be a change in the bukkit API:

Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_NOTE_HAT
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_181]
        at org.bukkit.Sound.valueOf(Sound.java:1) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
        at me.kangarko.compatbridge.model.CompSound.parseSound(CompSound.java:80) ~[?:?]
        at me.kangarko.compatbridge.model.CompSound.<init>(CompSound.java:72) ~[?:?]
        at me.kangarko.compatbridge.model.CompSound.<clinit>(CompSound.java:13) ~[?:?]
        at net.lapismc.HomeSpawn.ui.UIDesignerAPI.<clinit>(UIDesignerAPI.java:36) ~[?:?]
        at net.lapismc.homespawn.playerdata.HomeSpawnPlayer.showHomesGUI(HomeSpawnPlayer.java:177) ~[?:?]
        at net.lapismc.homespawn.commands.HomeSpawnHomeList.onCommand(HomeSpawnHomeList.java:46) ~[?:?]
        at net.lapismc.homespawn.util.LapisCommand.execute(LapisCommand.java:137) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]

**Pull request merged**
